config/routes.rb
Rails.application.routes.draw do
  get 'genres/index'
  get 'genres/show'
  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  resources :books
  resources :authors
  resources :genres
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
    validates :genre_name, presence: true
    
    def self.ransackable_attributes(auth_object = nil)
        %w[genre_name created_at updated_at]
      end
    def self.ransackable_associations(auth_object = nil)
        ["books"]
     end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @books = @genre.books
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<h1>All Genres</h1>
<% if customer_signed_in? %>
  <p>Welcome <%= current_customer.username %>!</p>
  <%= form_tag destroy_customer_session_path, method: :delete do %>
    <%= submit_tag "Logout" %>
  <% end %>  <% else %>
  <%= link_to 'Login', new_customer_session_path %>
<% end %>

<li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'Books', books_path %></li>
<li><%= link_to 'Genres', genres_path %></li>
<li><%= link_to 'Authors', authors_path %></li><br/>

<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.genre_name, genre_path(genre) %>
    </li>
  <% end %>
</ul>

app/views/genres/show.html.erb
<h1><%= @genre.genre_name %></h1>
<% if customer_signed_in? %>
  <p>Welcome <%= current_customer.username %>!</p>
  <%= form_tag destroy_customer_session_path, method: :delete do %>
    <%= submit_tag "Logout" %>
  <% end %>  <% else %>
  <%= link_to 'Login', new_customer_session_path %>
<% end %>
<li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'Books', books_path %></li>
<li><%= link_to 'Genres', genres_path %></li>
<li><%= link_to 'Authors', authors_path %></li>
<h2>Books in <%= @genre.genre_name %></h2>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.book_name, book_path(book) %></li>
  <% end %>
</ul>